### ISSUE TITLE
Ajout de slot pour les clients beger

### ISSUE THREAD

**Issue by Jimocu** [Lunastellia/LethalCorporation#4]
Bonjour, il y a un beg avec la stats "charisme", pour l’hôte de la partie pas de problème, en revanche quand mes amis ajoute des points pour avoir un emplacement en plus, l'emplacement n'apparait pas, seul l'hote peut utilisé cette stats
Dans la console de logs il est bien affiché "to add 1 slots" quand ils ajoute 10 point dedans, mais l'emplacement n'apparait pas cher eux, et il sont bien limité à 4 items

**Comment by Jimocu** [comment]
Dans la console de logs il est bien affiché "to add 1 slots" quand ils ajoute 10 point dedans, mais l'emplacement n'apparait pas cher eux, et il sont bien limité à 4 items

**Comment by Lunastellia** [comment]
Bonjour, 

En effet un autre signalement la dessus à étais fait, je vais travailler dessus pour voir d'où viens le problème, merci pour le signalement de bug ;)

**Comment by Jimocu** [comment]
Ha je n'ai pas vu l'autre signalement désolé, merci pour ta réponse rapide :)
Utilisant late game upgrade en complément, j'ai trouvé ta version hier et j'ai pu retravaillé l'équilibrage et moi et mes amis adorons les upgrade de perso que tu propose pour laisser LGU seulement au up d'équipement 
J'espère que tu trouveras d’où viens le problème de synchro 😁

**Comment by Lunastellia** [comment]
Aaha j'utilise aussi lategame upgrade pour les items uniquement, c'est très bien ;) c'est en effet à éviter d'utiliser les 2 sur les modifs de stats sa pourrais faire conflit ;) je suis en train de faire du debugg mais je dois attendre dans la soirée pour faire les test (impossible de tester solo du coup^^)

merci pour t'es retours ;) si vous avez des idées éventuel de stats ou autres à ajouter n'hésite pas !

**Comment by Jimocu** [comment]
Oui pas de soucis la dessus j'ai désactivé ces options dans LGU, je tiens à avoir un équilibrage (que ce soit ça ou les lune intérieurs, scrap trouvable prix ect..)
Si tu veux on peut se call discord pour voir si ton debugg fonctionne, si tu as du temps bien sûr: jimocu53

**Comment by Lunastellia** [comment]
Je ne suis plus dispo là immédiatement ^^ mais je t'ajoute en ami, pour l'occasion
